import 'package:flutter/material.dart';

class AppStrings {
  static const supportedLocales = [Locale('en'), Locale('ar')];

  static String of(BuildContext context, String key) {
    final lang = Localizations.localeOf(context).languageCode;
    return (_values[lang] ?? _values['en']!)[key] ?? _values['en']![key] ?? key;
  }

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'appName': 'School Management',
      'startNow': 'Start Now',
      'onboardingTitle': 'Learn anything anytime anywhere',
      'onboardingBody':
          'Manage students, teachers, classes, attendance, fees, exams and parents from one mobile workspace.',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'apiBaseUrl': 'API base URL',
      'dashboard': 'Dashboard',
      'students': 'Students',
      'teachers': 'Teachers',
      'parents': 'Parents',
      'grades': 'Grades',
      'classrooms': 'Classrooms',
      'sections': 'Sections',
      'subjects': 'Subjects',
      'attendance': 'Attendance',
      'fees': 'Fees',
      'feeInvoices': 'Fee invoices',
      'receipts': 'Receipts',
      'processingFees': 'Processing fees',
      'payments': 'Payments',
      'library': 'Library',
      'onlineClasses': 'Online classes',
      'quizzes': 'Quizzes',
      'questions': 'Questions',
      'settings': 'Settings',
      'profile': 'Profile',
      'search': 'Search',
      'add': 'Add',
      'edit': 'Edit',
      'delete': 'Delete',
      'save': 'Save',
      'cancel': 'Cancel',
      'confirmDelete': 'Delete this item?',
      'noData': 'No data yet',
      'retry': 'Retry',
      'logout': 'Logout',
      'language': 'Language',
      'english': 'English',
      'arabic': 'Arabic',
      'name': 'Name',
      'arabicName': 'Arabic name',
      'englishName': 'English name',
      'amount': 'Amount',
      'date': 'Date',
      'description': 'Description',
      'grade': 'Grade',
      'classroom': 'Classroom',
      'section': 'Section',
      'gender': 'Gender',
      'nationality': 'Nationality',
      'bloodType': 'Blood type',
      'birthDate': 'Birth date',
      'academicYear': 'Academic year',
      'parent': 'Parent',
      'teacher': 'Teacher',
      'subject': 'Subject',
      'present': 'Present',
      'absent': 'Absent',
      'attendanceToday': 'Today attendance',
      'markAttendance': 'Mark attendance',
      'fatherInfo': 'Father information',
      'motherInfo': 'Mother information',
      'contactInfo': 'Contact information',
      'joiningDate': 'Joining date',
      'specialization': 'Specialization',
      'address': 'Address',
      'phone': 'Phone',
      'nationalId': 'National ID',
      'job': 'Job',
      'statsStudents': 'Students',
      'statsTeachers': 'Teachers',
      'statsClasses': 'Classes',
      'recentWorkflows': 'Workflows',
      'cms': 'CMS',
      'cmsSubtitle':
          'Create, edit, review, and manage all school content modules.',
      'people': 'People',
      'academics': 'Academics',
      'finance': 'Finance',
      'learning': 'Learning',
      'exams': 'Exams',
      'studentsWorkflow': 'Student workflows',
      'lookups': 'Lookups',
      'system': 'System',
      'schoolRecords': 'School records',
      'crud': 'CRUD',
      'readOnly': 'Read only',
      'graduated': 'Graduated students',
      'promotion': 'Promotions',
      'specializations': 'Specializations',
      'genders': 'Genders',
      'nationalities': 'Nationalities',
      'bloodTypes': 'Blood types',
      'studentIds': 'Student IDs',
      'graduationDate': 'Graduation date',
      'promotionDate': 'Promotion date',
      'notes': 'Notes',
      'fromGrade': 'From grade',
      'fromClassroom': 'From classroom',
      'fromSection': 'From section',
      'toGrade': 'To grade',
      'toClassroom': 'To classroom',
      'toSection': 'To section',
      'navError': 'Navigation error',
      'forgotPassword': 'Forgot password?',
      'changePortal': 'Change portal',
      'createAccount': 'Create account',
      'resetLinkSent': 'Reset link sent',
      'sendResetLink': 'Send reset link',
      'checkEmailVerify': 'Please check your email to verify your account.',
      'resendVerifyEmail': 'Resend verification email',
      'savedSuccessfully': 'Saved successfully',
      'actions': 'Actions',
      'create': 'Create',
      'fewMinutesAgo': 'A few minutes ago',
      'recentGrades': 'Recent grades',
      'recentGradesDesc': 'Math 92%, Science 88%, Arabic 95%',
      'recentAlert': 'Recent alert',
      'recentAlertDesc': 'New receipt is available for download.',
      'late': 'Late',
      'exportShare': 'Export/share',
      'previous': 'Previous',
      'next': 'Next',
      'back': 'Back',
      'tuitionFee': 'Tuition fee',
      'unpaid200': 'Unpaid - \$200',
      'receipt1021': 'Receipt #1021',
      'paidDownload': 'Paid - Download available',
      'academicMotherDetails': 'Academic / Mother details',
      'reviewLinkRecords': 'Review and link records',
      'confirmLinked': 'Confirm linked children, parent, or academic data.',
      'quizDetail': 'Quiz detail',
      'addQuestion': 'Add question',
      'mathSectionA': '08:00 - Math / Section A',
      'choosePortal': 'Choose your portal',
      'selectRole': 'Select the role you want to preview or sign in with.',
      'screensAndWorkflows': 'screens and workflows',
    },
    'ar': {
      'appName': 'نظام إدارة المدرسة',
      'startNow': 'ابدأ الآن',
      'onboardingTitle': 'تعلم في أي وقت ومن أي مكان',
      'onboardingBody':
          'إدارة الطلاب والمعلمين والفصول والحضور والرسوم والاختبارات وأولياء الأمور من تطبيق واحد.',
      'login': 'تسجيل الدخول',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'apiBaseUrl': 'رابط واجهة البرمجة',
      'dashboard': 'لوحة التحكم',
      'students': 'الطلاب',
      'teachers': 'المعلمون',
      'parents': 'أولياء الأمور',
      'grades': 'المراحل',
      'classrooms': 'الفصول',
      'sections': 'الأقسام',
      'subjects': 'المواد',
      'attendance': 'الحضور',
      'fees': 'الرسوم',
      'feeInvoices': 'فواتير الرسوم',
      'receipts': 'سندات القبض',
      'processingFees': 'استبعاد الرسوم',
      'payments': 'سندات الصرف',
      'library': 'المكتبة',
      'onlineClasses': 'الحصص الأونلاين',
      'quizzes': 'الاختبارات',
      'questions': 'الأسئلة',
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'search': 'بحث',
      'add': 'إضافة',
      'edit': 'تعديل',
      'delete': 'حذف',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'confirmDelete': 'هل تريد حذف هذا العنصر؟',
      'noData': 'لا توجد بيانات',
      'retry': 'إعادة المحاولة',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'name': 'الاسم',
      'arabicName': 'الاسم بالعربية',
      'englishName': 'الاسم بالإنجليزية',
      'amount': 'المبلغ',
      'date': 'التاريخ',
      'description': 'الوصف',
      'grade': 'المرحلة',
      'classroom': 'الفصل',
      'section': 'القسم',
      'gender': 'الجنس',
      'nationality': 'الجنسية',
      'bloodType': 'فصيلة الدم',
      'birthDate': 'تاريخ الميلاد',
      'academicYear': 'السنة الأكاديمية',
      'parent': 'ولي الأمر',
      'teacher': 'المعلم',
      'subject': 'المادة',
      'present': 'حضور',
      'absent': 'غياب',
      'attendanceToday': 'حضور اليوم',
      'markAttendance': 'تسجيل الحضور',
      'fatherInfo': 'معلومات الأب',
      'motherInfo': 'معلومات الأم',
      'contactInfo': 'معلومات التواصل',
      'joiningDate': 'تاريخ الانضمام',
      'specialization': 'التخصص',
      'address': 'العنوان',
      'phone': 'الهاتف',
      'nationalId': 'الرقم الوطني',
      'job': 'الوظيفة',
      'statsStudents': 'الطلاب',
      'statsTeachers': 'المعلمون',
      'statsClasses': 'الفصول',
      'recentWorkflows': 'سير العمل',
      'cms': 'إدارة المحتوى',
      'cmsSubtitle': 'إنشاء وتعديل ومراجعة وإدارة كل وحدات النظام المدرسي.',
      'people': 'الأشخاص',
      'academics': 'الأكاديميات',
      'finance': 'المالية',
      'learning': 'التعلم',
      'exams': 'الاختبارات',
      'studentsWorkflow': 'إجراءات الطلاب',
      'lookups': 'القوائم المرجعية',
      'system': 'النظام',
      'schoolRecords': 'سجلات المدرسة',
      'crud': 'إدارة كاملة',
      'readOnly': 'عرض فقط',
      'graduated': 'الطلاب المتخرجون',
      'promotion': 'الترقيات',
      'specializations': 'التخصصات',
      'genders': 'الجنس',
      'nationalities': 'الجنسيات',
      'bloodTypes': 'فصائل الدم',
      'studentIds': 'أرقام الطلاب',
      'graduationDate': 'تاريخ التخرج',
      'promotionDate': 'تاريخ الترقية',
      'notes': 'ملاحظات',
      'fromGrade': 'من المرحلة',
      'fromClassroom': 'من الفصل',
      'fromSection': 'من القسم',
      'toGrade': 'إلى المرحلة',
      'toClassroom': 'إلى الفصل',
      'toSection': 'إلى القسم',
      'navError': 'خطأ في التوجيه',
      'forgotPassword': 'هل نسيت كلمة المرور؟',
      'changePortal': 'تغيير البوابة',
      'createAccount': 'إنشاء حساب',
      'resetLinkSent': 'تم إرسال رابط الاستعادة',
      'sendResetLink': 'إرسال رابط الاستعادة',
      'checkEmailVerify': 'يرجى التحقق من بريدك الإلكتروني لتأكيد حسابك.',
      'resendVerifyEmail': 'إعادة إرسال بريد التأكيد',
      'savedSuccessfully': 'تم الحفظ بنجاح',
      'actions': 'الإجراءات',
      'create': 'إنشاء',
      'fewMinutesAgo': 'منذ بضع دقائق',
      'recentGrades': 'أحدث الدرجات',
      'recentGradesDesc': 'الرياضيات 92٪، العلوم 88٪، العربية 95٪',
      'recentAlert': 'تنبيه حديث',
      'recentAlertDesc': 'إيصال جديد متاح للتحميل.',
      'late': 'متأخر',
      'exportShare': 'تصدير / مشاركة',
      'previous': 'السابق',
      'next': 'التالي',
      'back': 'رجوع',
      'tuitionFee': 'الرسوم الدراسية',
      'unpaid200': 'غير مدفوع - \$200',
      'receipt1021': 'إيصال #1021',
      'paidDownload': 'مدفوع - متاح للتحميل',
      'academicMotherDetails': 'التفاصيل الأكاديمية / تفاصيل الأم',
      'reviewLinkRecords': 'مراجعة وربط السجلات',
      'confirmLinked':
          'تأكيد بيانات الأطفال المرتبطة، ولي الأمر، أو البيانات الأكاديمية.',
      'quizDetail': 'تفاصيل الاختبار',
      'addQuestion': 'إضافة سؤال',
      'mathSectionA': '08:00 - الرياضيات / القسم أ',
      'choosePortal': 'اختر بوابتك',
      'selectRole': 'حدد الدور الذي تريد معاينته أو تسجيل الدخول به.',
      'screensAndWorkflows': 'شاشات وإجراءات',
    },
  };
}
